name: flutter_gastro_go
description: "Um breve restaurante"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-154.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  mobx_codegen: ^2.7.4
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
