name: flutter_gastro_go
description: "Um breve restaurante"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-154.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  intl: any
  objectbox: ^5.0.1
  objectbox_flutter_libs: any
  path_provider: ^2.1.5
  path: ^1.9.1
  go_router: ^16.3.0
  lottie: ^3.3.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  mobx_codegen: ^2.7.4
  json_serializable: ^6.10.0
  mockito: ^5.0.0
  objectbox_generator: any

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/
    - assets/data/
    - assets/data/restaurants.json
    - assets/data/dishes.json
    - assets/images/
    - assets/images/banners/
    - assets/images/categories/
    - assets/images/dishes/
    - assets/images/others/
    - assets/images/restaurants/
    - assets/images/icons/
    - assets/images/lotties/
