// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/favorite/domain/entities/favorite_dish_entity.dart';
import 'features/favorite/domain/entities/favorite_restaurant_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3957488468033634429),
    name: 'FavoriteDishEntity',
    lastPropertyId: const obx_int.IdUid(3, 3526909477873885423),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4361990735166685108),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8492321400459667449),
        name: 'dishId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 1847870631306520119),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3526909477873885423),
        name: 'restaurantId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6074145313777160419),
    name: 'FavoriteRestaurantEntity',
    lastPropertyId: const obx_int.IdUid(2, 3200342709155434881),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3050376649149458078),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3200342709155434881),
        name: 'restaurantId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 7095250535791898355),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 6074145313777160419),
    lastIndexId: const obx_int.IdUid(2, 7095250535791898355),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FavoriteDishEntity: obx_int.EntityDefinition<FavoriteDishEntity>(
      model: _entities[0],
      toOneRelations: (FavoriteDishEntity object) => [],
      toManyRelations: (FavoriteDishEntity object) => {},
      getId: (FavoriteDishEntity object) => object.id,
      setId: (FavoriteDishEntity object, int id) {
        object.id = id;
      },
      objectToFB: (FavoriteDishEntity object, fb.Builder fbb) {
        final dishIdOffset = fbb.writeString(object.dishId);
        final restaurantIdOffset = object.restaurantId == null
            ? null
            : fbb.writeString(object.restaurantId!);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, dishIdOffset);
        fbb.addOffset(2, restaurantIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = FavoriteDishEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..dishId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..restaurantId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 8);

        return object;
      },
    ),
    FavoriteRestaurantEntity:
        obx_int.EntityDefinition<FavoriteRestaurantEntity>(
          model: _entities[1],
          toOneRelations: (FavoriteRestaurantEntity object) => [],
          toManyRelations: (FavoriteRestaurantEntity object) => {},
          getId: (FavoriteRestaurantEntity object) => object.id,
          setId: (FavoriteRestaurantEntity object, int id) {
            object.id = id;
          },
          objectToFB: (FavoriteRestaurantEntity object, fb.Builder fbb) {
            final restaurantIdOffset = fbb.writeString(object.restaurantId);
            fbb.startTable(3);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, restaurantIdOffset);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);

            final object = FavoriteRestaurantEntity()
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..restaurantId = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 6, '');

            return object;
          },
        ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FavoriteDishEntity] entity fields to define ObjectBox queries.
class FavoriteDishEntity_ {
  /// See [FavoriteDishEntity.id].
  static final id = obx.QueryIntegerProperty<FavoriteDishEntity>(
    _entities[0].properties[0],
  );

  /// See [FavoriteDishEntity.dishId].
  static final dishId = obx.QueryStringProperty<FavoriteDishEntity>(
    _entities[0].properties[1],
  );

  /// See [FavoriteDishEntity.restaurantId].
  static final restaurantId = obx.QueryStringProperty<FavoriteDishEntity>(
    _entities[0].properties[2],
  );
}

/// [FavoriteRestaurantEntity] entity fields to define ObjectBox queries.
class FavoriteRestaurantEntity_ {
  /// See [FavoriteRestaurantEntity.id].
  static final id = obx.QueryIntegerProperty<FavoriteRestaurantEntity>(
    _entities[1].properties[0],
  );

  /// See [FavoriteRestaurantEntity.restaurantId].
  static final restaurantId = obx.QueryStringProperty<FavoriteRestaurantEntity>(
    _entities[1].properties[1],
  );
}
