name: Flutter CI

# (Em todo 'push' para a branch 'main' ou em 'pull_requests')
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    # O tipo de máquina que o robô vai usar (Ubuntu é o mais comum)
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o seu código para a máquina do robô
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      # 2. Instala o Java (necessário para 'build apk')
      - name: 2. Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Instala o Flutter SDK
      - name: 3. Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # Use a versão do Flutter que você está usando localmente
          flutter-version: '3.38.0-0.2.pre' 
          channel: 'master'
          cache: true # Habilita o cache para acelerar builds futuros

      # 4. Instala as dependências do seu app
      - name: 4. Install dependencies
        run: flutter pub get

      # 5. Roda o Linter 
      - name: 5. Run Analyzer
        run: flutter analyze

      # 6. Roda os Testes
      - name: 6. Run Tests
        run: flutter test

      # 7. Compila o App
      - name: 7. Build APK (Debug)
        run: flutter build apk --debug